version: '3.0'
services:
  redis:
    image: 'redis/redis-stack'
    ports:
      - '6379:6379'
      - '8001:8001'
    build:
      context: ./redis/
      dockerfile: Dockerfile
    networks:
      - urlnet
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app/
    depends_on:
      - redis
    networks:
      - urlnet
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - static_content:/dist/
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - static_content:/www/eldon/zone/
    networks:
      - urlnet
    environment:
      SITE_URL: $SITE_URL
      API_URL: $API_URL
    depends_on:
      - backend
      - frontend

networks:
  urlnet:

volumes:
  caddy_data:
    external: true
  caddy_config:
  static_content:
